# general settings
name: 101_EDVR_OURs_1  #101_EDVR_OURs_nopredebuler
model_type: EDVRModel
scale: 1
num_gpu: 2 # set num_gpu: 0 for cpu mode
manual_seed: 10
#gpu_ids：[3,4]
# dataset and data loader settings
datasets:
  train:
    name: redsofficial
    type: REDSDataset
    dataroot_gt: /home/yzt/EDVR/datasets/VideoHazy_v2_re/Train/gt
    dataroot_lq: /home/yzt/EDVR/datasets/VideoHazy_v2_re/Train/hazy  #dx_Res_JPG
    dataroot_flow: ~
    meta_info_file: /home/yzt/EDVR/basicsr/data/meta_info/train_.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    num_frame: 5
    gt_size: 128
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: redsofficial
    type: VideoTestDataset
    dataroot_gt: /home/yzt/EDVR/datasets/VideoHazy_v2_re/Test/crop_gt
    dataroot_lq: /home/yzt/EDVR/datasets/VideoHazy_v2_re/Test/crop_hazy
    meta_info_file: /home/yzt/EDVR/basicsr/data/meta_info/test_.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

    cache_data: false
    num_frame: 5
    padding: reflection_circle

# network structures
network_g:
  type: EDVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_frame: 5
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 10
  center_frame_idx: ~
  hr_in: true
  with_predeblur: true
  with_tsa: true

# path
path:
  pretrain_model_g: ~
  strict_load: true
  resume_state: /home/yzt/EDVR/experiments/101_EDVR_OURs_1/training_states/129000.state   # /home/yzt/EDVR/experiments/101_EDVR_OURs/training_states/8500.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000, 150000, 150000, 150000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 3.3e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 2000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 2000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
